A_philosophies = [
	'Actualism',
	'Advaita Vedanta',
	'Aesthetic Realism',
	'Aesthetics',
	'Agential realism',
	'Ancient philosophy',
	'Atheism',
	'Averroism',
	'Avicennism',
	'Axiology',
	'Baptism',
	'Behaviorism',
	'Bayesian probability',
	'Bioconservatism',
	'Philosophy of biology',
	'Philosophy of business',
	'Cartesianism',
	'Categorical imperative',
	'Christian humanism',
	'Communism',
	'Scottish common sense realism',
	'Communitrianism',
	'Confirmation holism',
	'Confucianism',
	'Consequentialism',
	'Conceptualism',
	'Conservatism',
	'Continental philosophy',
	'Cosmopolitanism',
	'Critical rationalism',
	'Critical realism',
	'Critical theory',
	'Cynicism',
	'Deconstruction',
	'Denialism',
	'Digital physics',
	'Discordianism',
	'Philosophy of eating',
	'Ecocentrism',
	'Philosophy of economics',
	'Egalitarianism',
	'Egocentrism',
	'Egoism',
	'Eliminative meterialism',
	'Emotivism',
	'Empiricism',
	'Philosophy of engineering',
	'Ephesian school',
	'Epiphenomenalism',
	'Epicureanism',
	'Epistemological nihilism',
	'Epistemology',
	'Esotericism',
	'Essentialism',
	'Ethics',
	'Eternalism',
	'Eudaimonism',
	'Existentialism',
	'Externalism',
	'Fallibilism',
	'Fascism',
	'Fatalism',
	'Feminist philosophy',
	'Filial piety',
	'Philosophy of film',
	'Foundationalism',
	'Free will',
	'Fundamentalism',
	'Philosophy of futility',
	'Philosophy of geography',
	'German idealism',
	'German philosophy',
	'Gnosticism',
	'Greek philosophy',
	'Philosophy of healthcare',
	'Hedonism',
	'Hegelianism',
	'Hermeticism',
	'Henotheism',
	'Heterophenomenology',
	'Hindu philosophy',
	'Historical materialism',
	'Historicism',
	'Philosophy of history',
	'Holism',
	'Hongaku',
	'Humanism',
	'Humanistic naturalism',
	'Hylozoism',
	'Idealism',
	'Identityism',
	'Ideological criticism',
	'Ignosticism',
	'Illegalism',
	'Illuminationism',
	'Individualism',
	'Indian logic',
	'Indian philosophy',
	'Indonesian philosophy',
	'Inductive reasoning',
	'Inductionism',
	'Informal logic',
	'Philosophy of information',
	'Innatism',
	'Instrumental rationality',
	'Instrumentalism',
	'Interactionism (philosophy of mind)',
	'Internalism and externalism',
	'Intuitionism',
	'Iranian philosophy',
	'Irrealism',
	'Islamic ethics',
	'Islamic philosophy',
	'Japanese philosophy',
	'Jainism',
	'Jewish philosophy',
	'Jingoism',
	'Juche',
	'Judeo-islamic philosophies (800–1400)',
	'Just war theory',
	'Kabbalah',
	'Kantianism',
	'Korean philosophy',
	'Philosophy of language',
	'Philosophy of law',
	'Legalism',
	'Leninism',
	'Liberalism',
	'Libertarianism',
	'Libertarianism (metaphysics)',
	'Philosophy of linguistics',
	'Logic in China',
	'Logic in Islamic philosophy',
	'Philosophy of logic',
	'Logical atomism',
	'Logical positivism',
	'Logicians',
	'Logicism',
	'Philosophy of love',
	'Luddism',
	'Mahayana Buddhism',
	'Manichaeism',
	'Maoism',
	'Marxism',
	'Marxist philosophy of nature',
	'Materialism',
	'Mathematicism',
	'Philosophy of mathematics education',
	'Philosophy of mathematics',
	'Maxim (philosophy)',
	'Medical ethics',
	'Medieval philosophy',
	'Medievalism',
	'Mentalism',
	'Mereological nihilism',
	'Merism',
	'Meta-ethics',
	'Meta-philosophy',
	'Metaphysics',
	'Milesian school',
	'Mimamsa',
	'Mind-body dualism',
	'Philosophy of mind',
	'Misology',
	'Modern Islamic philosophy',
	'Modernism',
	'Mohism',
	'Monism',
	'Moral absolutism',
	'Moral realism',
	'Moral relativism',
	'Moral skepticism',
	'Philosophy of motion',
	'Philosophy of music',
	'Mysticism',
	'Naïve realism',
	'Naturphilosophie',
	'Naturalism',
	'Philosophy of natural Science',
	'Nazism',
	'Negative utilitarianism',
	'Neo-Confucianism',
	'Neoconservatism',
	'Neo-Hegelianism',
	'Neoliberalism',
	'Neo-Kantianism',
	'Neo-Luddism',
	'Neoplatonism',
	'Neopythagoreanism',
	'Neo-Scholasticism',
	'Neotaoism',
	'Neuroethics',
	'Neurophilosophy',
	'Philosophy of natural Science',
	'Neurotheology',
	'Neutral monism',
	'New Age',
	'New realism',
	'New Thought',
	'Nihilism',
	'Nominalism',
	'Non-cognitivism',
	'Non-dualism',
	'Non-philosophy',
	'Non-theism',
	'Nyaya',
	'Objective idealism',
	'Objectivism',
	'Occasionalism',
	'Ontology',
	'Ontotheology',
	'Open individualism',
	'Organicism',
	'Paganism',
	'Pakistani philosophy',
	'Pancritical rationalism',
	'Pandeism',
	'Panpsychism',
	'Pantheism',
	'Pataphysics',
	'Philosophy of perception',
	'Perennial philosophy',
	'Perfectionism',
	'Peripatetic school',
	'Personalism',
	'Perspectivism',
	'Pessimism',
	'Phenomenalism',
	'Phenomenology',
	'Philosophical anthropology',
	'Philosophical Satanism',
	'Metaphilosophy',
	'Physical ontology',
	'Physicalism',
	'Philosophy of physics',
	'Platonic realism',
	'Platonism',
	'Pluralism',
	'Political philosophy',
	'Populism',
	'Posadism',
	'Positivism',
	'Postanalytic philosophy',
	'Posthumanism',
	'Post-materialism',
	'Postmodernism',
	'Postpositivism',
	'Post-structuralism',
	'Practical reason',
	'Pragmatism',
	'Praxis School',
	'Presentism',
	'Probabilism',
	'Process philosophy',
	'Progressivism',
	'Property dualism',
	'Philosophy of psychiatry',
	'Psych',
	'Psychological egoism',
	'Philosophy of psychology',
	'Pure practical reason',
	'Pure reason',
	'Pyrrhonian skepticism',
	'Pyrrhonism',
	'Pythagoreanism',
	'Quantum mysticism',
	'Quietism',
	'Raëlism',
	'Rastafari',
	'Rationalism',
	'Realism',
	'Reconstructivism',
	'Reductionism',
	'Reductive materialism',
	'Reformational philosophy',
	'Relationalism',
	'Relativism',
	'Relevance logic',
	'Philosophy of religion',
	'Philosophy of religious language',
	'Religious humanism',
	'Religious philosophy',
	'Reliabilism',
	'Renaissance humanism',
	'Romanian philosophy',
	'Romanticism',
	'Russian cosmism',
	'Russian philosophy',
	'Sabellianism',
	'Satanism',
	'Sankhya',
	'Scotism',
	'Scholasticism',
	'Philosophy of science',
	'Scientism',
	'Secularism',
	'Secular humanism',
	'Philosophy of self',
	'Semantic holism',
	'Sensualism',
	'Philosophy of sex',
	'Sexualism',
	'Sexism',
	'Shamanism',
	'Sikhism',
	'Singularitarianism',
	'Skepticism',
	'Skeptical theism',
	'Philosophy of social science',
	'Socialism',
	'Social philosophy',
	'Solipsism',
	'Sophism',
	'Philosophy of space and time',
	'Spiritual philosophy',
	'Spiritualism',
	'Philosophy of sport',
	'Philosophy of statistics',
	'Stoicism',
	'Structuralism',
	'Subjective idealism',
	'Subjectivism',
	'Sufi metaphysics',
	'Śūnyatā',
	'Supersessionism',
	'Synoptic philosophy',
	'Systems philosophy',
	'Taoism',
	'Teleology',
	'Tetralemma',
	'Theistic finitism',
	'Theism',
	'Thelema',
	'Theology',
	'Theosophy',
	'Philosophy of thermal and statistical physics',
	'Thomism',
	'Theravada Buddhism',
	'Traditionalist School',
	'Transcendent theosophy',
	'Transcendental idealism',
	'Transcendental perspectivism',
	'Transcendentalism',
	'Transhumanism',
	'Transmodernism',
	'Type physicalism',
	'Ubuntu',
	'Universalism',
	'Utilitarian bioethics',
	'Utilitarianism',
	'Value pluralism',
	'Value theory',
	'Vedanta',
	'Verificationism',
	'Verism',
	'Vienna Circle',
	'Virtue ethics',
	'Vitalism',
	'Voluntaryism',
	'Wahdat-ul-Wujood',
	'Wahdat-ul-Shuhud',
	'Philosophy of war',
	'Western philosophy',
	'Wu wei',
	'Xenofeminism',
	'Zemlyak',
	'Zen',
	'Zoroastrianism',
	'Zurvanism'
	]